site_name: Lens Extension Development
site_description: Documentation for Lens Extension Development and API.
site_author: Mirantis, Inc.
site_url: https://api-docs.k8slens.dev
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/lensapp/lens
copyright: Copyright &copy; 2021 <a href="https://mirantis.com/">Mirantis Inc.</a> - All rights reserved.
edit_uri: ""
nav:
  - Overview: README.md
  - Getting Started:
      - Overview: extensions/get-started/overview.md
      - Your First Extension: extensions/get-started/your-first-extension.md
      - Extension Anatomy: extensions/get-started/anatomy.md
      - Wrapping Up: extensions/get-started/wrapping-up.md
  - Extension Capabilities:
      - Common Capabilities: extensions/capabilities/common-capabilities.md
      - Styling: extensions/capabilities/styling.md
  - Extension Guides:
      - Overview: extensions/guides/README.md
      - Generator: extensions/guides/generator.md
      - Main Extension: extensions/guides/main-extension.md
      - Renderer Extension: extensions/guides/renderer-extension.md
      - Catalog: extensions/guides/catalog.md
      - Resource Stack: extensions/guides/resource-stack.md
      - Extending KubernetesCluster: extensions/guides/extending-kubernetes-cluster.md
      - Stores: extensions/guides/stores.md
      - Working with MobX: extensions/guides/working-with-mobx.md
      - Protocol Handlers: extensions/guides/protocol-handlers.md
      - IPC: extensions/guides/ipc.md
  - Testing and Publishing:
      - Testing Extensions: extensions/testing-and-publishing/testing.md
      - Publishing Extensions: extensions/testing-and-publishing/publishing.md
  - API Reference: extensions/api/README.md
theme:
  name: "material"
  highlightjs: true
  language: "en"
  custom_dir: docs/custom_theme
  favicon: img/favicon.ico
  logo: img/lens-logo-icon.svg
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - toc.autohide
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight: {}
  - pymdownx.superfences: {}
  - pymdownx.inlinehilite: {}
  - toc:
      permalink: "#"
      toc_depth: 3
  - admonition: {}
  - pymdownx.details: {}

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lensapp/lens
      name: Lens on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/k8slens
      name: Lens on Twitter
    - icon: fontawesome/brands/discourse
      link: https://forums.k8slens.dev/
      name: Lens Forums
    - icon: fontawesome/solid/link
      link: https://k8slens.dev/
      name: Lens Website
  version:
    provider: mike
  analytics:
    provider: google
    property: UA-159377374-2
