name: Check Documentation
on:
  pull_request:
    branches:
      - "**"
jobs:
  build:
    name: Check Docs
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'area/documentation') }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Release from lens
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install specific npm version
        run: npm install -g npm@^9.6.7

      - name: Generate Extensions API Reference using typedocs
        run: |
          npm install
          npm run build:docs

      - name: Verify that the markdown is valid
        run: |
          npm run mkdocs:verify
