name: Release Open Lens
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - release/v*.*
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release') }}
    outputs:
      version: ${{ steps.tagger.outputs.tagname }}
    steps:
      - name: Checkout Release from lens
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: butlerlogic/action-autotag@stable
        id: tagger
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          root: /packages/core
      - uses: ncipollo/release-action@v1
        if: ${{ steps.tagger.outputs.tagname != '' }}
        with:
          name: ${{ steps.tagger.outputs.tagname }}
          commit: master
          tag: ${{ steps.tagger.outputs.tagname }}
          body: ${{ github.event.pull_request.body }}
          prerelease: ${{ contains(steps.tagger.outputs.tagname, '-alpha.') || contains(steps.tagger.outputs.tagname, '-beta.') }}
  publish-npm:
    uses: ./.github/workflows/publish-release-npm.yml
    needs: release
    if: ${{ needs.release.outputs.version != '' }}
    secrets: inherit
    with:
      version: ${{ needs.release.outputs.version }}
